//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberSearch.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Number
    {
        public Number()
        {
            this.NumberOperators = new HashSet<NumberOperator>();
        }
    
        public long NumberID { get; set; }
        public string Number1 { get; set; }
        public string port_completion_time { get; set; }
    
        public virtual ICollection<NumberOperator> NumberOperators { get; set; }
    }
}
