//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberSearch.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberOperator
    {
        public long NumberOperatorID { get; set; }
        public int OperatorID { get; set; }
        public long NumberID { get; set; }
    
        public virtual Number Number { get; set; }
        public virtual Operator Operator { get; set; }
    }
}
