//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberSearch.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NumbersAndOperators
    {
        public string Number { get; set; }
        public long NumberOperatorID { get; set; }
        public int OperatorID { get; set; }
        public long NumberID { get; set; }
        public string Name { get; set; }
        public string description { get; set; }
        public string port_completion_time { get; set; }
    }
}
