//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ICN_NumberSearchModel", "FK_NumberOperator_Number", "Number", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NumberUpload.Number), "NumberOperator", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NumberUpload.NumberOperator), true)]
[assembly: EdmRelationshipAttribute("ICN_NumberSearchModel", "FK_NumberOperator_Operator", "Operator", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NumberUpload.Operator), "NumberOperator", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NumberUpload.NumberOperator), true)]

#endregion

namespace NumberUpload
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ICN_NumberSearchEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ICN_NumberSearchEntities object using the connection string found in the 'ICN_NumberSearchEntities' section of the application configuration file.
        /// </summary>
        public ICN_NumberSearchEntities() : base("name=ICN_NumberSearchEntities", "ICN_NumberSearchEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ICN_NumberSearchEntities object.
        /// </summary>
        public ICN_NumberSearchEntities(string connectionString) : base(connectionString, "ICN_NumberSearchEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ICN_NumberSearchEntities object.
        /// </summary>
        public ICN_NumberSearchEntities(EntityConnection connection) : base(connection, "ICN_NumberSearchEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CodePoint> CodePoints
        {
            get
            {
                if ((_CodePoints == null))
                {
                    _CodePoints = base.CreateObjectSet<CodePoint>("CodePoints");
                }
                return _CodePoints;
            }
        }
        private ObjectSet<CodePoint> _CodePoints;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Number> Numbers
        {
            get
            {
                if ((_Numbers == null))
                {
                    _Numbers = base.CreateObjectSet<Number>("Numbers");
                }
                return _Numbers;
            }
        }
        private ObjectSet<Number> _Numbers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NumberOperator> NumberOperators
        {
            get
            {
                if ((_NumberOperators == null))
                {
                    _NumberOperators = base.CreateObjectSet<NumberOperator>("NumberOperators");
                }
                return _NumberOperators;
            }
        }
        private ObjectSet<NumberOperator> _NumberOperators;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Operator> Operators
        {
            get
            {
                if ((_Operators == null))
                {
                    _Operators = base.CreateObjectSet<Operator>("Operators");
                }
                return _Operators;
            }
        }
        private ObjectSet<Operator> _Operators;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_Setting> tb_Setting
        {
            get
            {
                if ((_tb_Setting == null))
                {
                    _tb_Setting = base.CreateObjectSet<tb_Setting>("tb_Setting");
                }
                return _tb_Setting;
            }
        }
        private ObjectSet<tb_Setting> _tb_Setting;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UploadedFile> UploadedFiles
        {
            get
            {
                if ((_UploadedFiles == null))
                {
                    _UploadedFiles = base.CreateObjectSet<UploadedFile>("UploadedFiles");
                }
                return _UploadedFiles;
            }
        }
        private ObjectSet<UploadedFile> _UploadedFiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vw_NumbersAndOperators> vw_NumbersAndOperators
        {
            get
            {
                if ((_vw_NumbersAndOperators == null))
                {
                    _vw_NumbersAndOperators = base.CreateObjectSet<vw_NumbersAndOperators>("vw_NumbersAndOperators");
                }
                return _vw_NumbersAndOperators;
            }
        }
        private ObjectSet<vw_NumbersAndOperators> _vw_NumbersAndOperators;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CodePoints EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCodePoints(CodePoint codePoint)
        {
            base.AddObject("CodePoints", codePoint);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Numbers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNumbers(Number number)
        {
            base.AddObject("Numbers", number);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NumberOperators EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNumberOperators(NumberOperator numberOperator)
        {
            base.AddObject("NumberOperators", numberOperator);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Operators EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOperators(Operator @operator)
        {
            base.AddObject("Operators", @operator);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_Setting EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_Setting(tb_Setting tb_Setting)
        {
            base.AddObject("tb_Setting", tb_Setting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UploadedFiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUploadedFiles(UploadedFile uploadedFile)
        {
            base.AddObject("UploadedFiles", uploadedFile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vw_NumbersAndOperators EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovw_NumbersAndOperators(vw_NumbersAndOperators vw_NumbersAndOperators)
        {
            base.AddObject("vw_NumbersAndOperators", vw_NumbersAndOperators);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ICN_NumberSearchModel", Name="CodePoint")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CodePoint : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CodePoint object.
        /// </summary>
        /// <param name="code_point_id">Initial value of the code_point_id property.</param>
        /// <param name="operatorName">Initial value of the OperatorName property.</param>
        public static CodePoint CreateCodePoint(global::System.Int32 code_point_id, global::System.String operatorName)
        {
            CodePoint codePoint = new CodePoint();
            codePoint.code_point_id = code_point_id;
            codePoint.OperatorName = operatorName;
            return codePoint;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 code_point_id
        {
            get
            {
                return _code_point_id;
            }
            set
            {
                if (_code_point_id != value)
                {
                    Oncode_point_idChanging(value);
                    ReportPropertyChanging("code_point_id");
                    _code_point_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("code_point_id");
                    Oncode_point_idChanged();
                }
            }
        }
        private global::System.Int32 _code_point_id;
        partial void Oncode_point_idChanging(global::System.Int32 value);
        partial void Oncode_point_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String point_number
        {
            get
            {
                return _point_number;
            }
            set
            {
                Onpoint_numberChanging(value);
                ReportPropertyChanging("point_number");
                _point_number = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("point_number");
                Onpoint_numberChanged();
            }
        }
        private global::System.String _point_number;
        partial void Onpoint_numberChanging(global::System.String value);
        partial void Onpoint_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OperatorName
        {
            get
            {
                return _OperatorName;
            }
            set
            {
                OnOperatorNameChanging(value);
                ReportPropertyChanging("OperatorName");
                _OperatorName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OperatorName");
                OnOperatorNameChanged();
            }
        }
        private global::System.String _OperatorName;
        partial void OnOperatorNameChanging(global::System.String value);
        partial void OnOperatorNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ICN_NumberSearchModel", Name="Number")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Number : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Number object.
        /// </summary>
        /// <param name="numberID">Initial value of the NumberID property.</param>
        /// <param name="number1">Initial value of the Number1 property.</param>
        public static Number CreateNumber(global::System.Int64 numberID, global::System.String number1)
        {
            Number number = new Number();
            number.NumberID = numberID;
            number.Number1 = number1;
            return number;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 NumberID
        {
            get
            {
                return _NumberID;
            }
            set
            {
                if (_NumberID != value)
                {
                    OnNumberIDChanging(value);
                    ReportPropertyChanging("NumberID");
                    _NumberID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NumberID");
                    OnNumberIDChanged();
                }
            }
        }
        private global::System.Int64 _NumberID;
        partial void OnNumberIDChanging(global::System.Int64 value);
        partial void OnNumberIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Number1
        {
            get
            {
                return _Number1;
            }
            set
            {
                OnNumber1Changing(value);
                ReportPropertyChanging("Number1");
                _Number1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Number1");
                OnNumber1Changed();
            }
        }
        private global::System.String _Number1;
        partial void OnNumber1Changing(global::System.String value);
        partial void OnNumber1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String port_completion_time
        {
            get
            {
                return _port_completion_time;
            }
            set
            {
                Onport_completion_timeChanging(value);
                ReportPropertyChanging("port_completion_time");
                _port_completion_time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("port_completion_time");
                Onport_completion_timeChanged();
            }
        }
        private global::System.String _port_completion_time;
        partial void Onport_completion_timeChanging(global::System.String value);
        partial void Onport_completion_timeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ICN_NumberSearchModel", "FK_NumberOperator_Number", "NumberOperator")]
        public EntityCollection<NumberOperator> NumberOperators
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NumberOperator>("ICN_NumberSearchModel.FK_NumberOperator_Number", "NumberOperator");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NumberOperator>("ICN_NumberSearchModel.FK_NumberOperator_Number", "NumberOperator", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ICN_NumberSearchModel", Name="NumberOperator")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NumberOperator : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NumberOperator object.
        /// </summary>
        /// <param name="numberOperatorID">Initial value of the NumberOperatorID property.</param>
        /// <param name="operatorID">Initial value of the OperatorID property.</param>
        /// <param name="numberID">Initial value of the NumberID property.</param>
        public static NumberOperator CreateNumberOperator(global::System.Int64 numberOperatorID, global::System.Int32 operatorID, global::System.Int64 numberID)
        {
            NumberOperator numberOperator = new NumberOperator();
            numberOperator.NumberOperatorID = numberOperatorID;
            numberOperator.OperatorID = operatorID;
            numberOperator.NumberID = numberID;
            return numberOperator;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 NumberOperatorID
        {
            get
            {
                return _NumberOperatorID;
            }
            set
            {
                if (_NumberOperatorID != value)
                {
                    OnNumberOperatorIDChanging(value);
                    ReportPropertyChanging("NumberOperatorID");
                    _NumberOperatorID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NumberOperatorID");
                    OnNumberOperatorIDChanged();
                }
            }
        }
        private global::System.Int64 _NumberOperatorID;
        partial void OnNumberOperatorIDChanging(global::System.Int64 value);
        partial void OnNumberOperatorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OperatorID
        {
            get
            {
                return _OperatorID;
            }
            set
            {
                OnOperatorIDChanging(value);
                ReportPropertyChanging("OperatorID");
                _OperatorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OperatorID");
                OnOperatorIDChanged();
            }
        }
        private global::System.Int32 _OperatorID;
        partial void OnOperatorIDChanging(global::System.Int32 value);
        partial void OnOperatorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 NumberID
        {
            get
            {
                return _NumberID;
            }
            set
            {
                OnNumberIDChanging(value);
                ReportPropertyChanging("NumberID");
                _NumberID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumberID");
                OnNumberIDChanged();
            }
        }
        private global::System.Int64 _NumberID;
        partial void OnNumberIDChanging(global::System.Int64 value);
        partial void OnNumberIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ICN_NumberSearchModel", "FK_NumberOperator_Number", "Number")]
        public Number Number
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Number>("ICN_NumberSearchModel.FK_NumberOperator_Number", "Number").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Number>("ICN_NumberSearchModel.FK_NumberOperator_Number", "Number").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Number> NumberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Number>("ICN_NumberSearchModel.FK_NumberOperator_Number", "Number");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Number>("ICN_NumberSearchModel.FK_NumberOperator_Number", "Number", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ICN_NumberSearchModel", "FK_NumberOperator_Operator", "Operator")]
        public Operator Operator
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Operator>("ICN_NumberSearchModel.FK_NumberOperator_Operator", "Operator").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Operator>("ICN_NumberSearchModel.FK_NumberOperator_Operator", "Operator").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Operator> OperatorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Operator>("ICN_NumberSearchModel.FK_NumberOperator_Operator", "Operator");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Operator>("ICN_NumberSearchModel.FK_NumberOperator_Operator", "Operator", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ICN_NumberSearchModel", Name="Operator")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Operator : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Operator object.
        /// </summary>
        /// <param name="operatorID">Initial value of the OperatorID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Operator CreateOperator(global::System.Int32 operatorID, global::System.String name)
        {
            Operator @operator = new Operator();
            @operator.OperatorID = operatorID;
            @operator.Name = name;
            return @operator;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OperatorID
        {
            get
            {
                return _OperatorID;
            }
            set
            {
                if (_OperatorID != value)
                {
                    OnOperatorIDChanging(value);
                    ReportPropertyChanging("OperatorID");
                    _OperatorID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OperatorID");
                    OnOperatorIDChanged();
                }
            }
        }
        private global::System.Int32 _OperatorID;
        partial void OnOperatorIDChanging(global::System.Int32 value);
        partial void OnOperatorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ICN_NumberSearchModel", "FK_NumberOperator_Operator", "NumberOperator")]
        public EntityCollection<NumberOperator> NumberOperators
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NumberOperator>("ICN_NumberSearchModel.FK_NumberOperator_Operator", "NumberOperator");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NumberOperator>("ICN_NumberSearchModel.FK_NumberOperator_Operator", "NumberOperator", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ICN_NumberSearchModel", Name="tb_Setting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_Setting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_Setting object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static tb_Setting Createtb_Setting(global::System.Int32 id, global::System.String name)
        {
            tb_Setting tb_Setting = new tb_Setting();
            tb_Setting.ID = id;
            tb_Setting.Name = name;
            return tb_Setting;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ICN_NumberSearchModel", Name="UploadedFile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UploadedFile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UploadedFile object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        /// <param name="processedDate">Initial value of the ProcessedDate property.</param>
        public static UploadedFile CreateUploadedFile(global::System.Int64 id, global::System.String fileName, global::System.DateTime processedDate)
        {
            UploadedFile uploadedFile = new UploadedFile();
            uploadedFile.ID = id;
            uploadedFile.FileName = fileName;
            uploadedFile.ProcessedDate = processedDate;
            return uploadedFile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ProcessedDate
        {
            get
            {
                return _ProcessedDate;
            }
            set
            {
                OnProcessedDateChanging(value);
                ReportPropertyChanging("ProcessedDate");
                _ProcessedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProcessedDate");
                OnProcessedDateChanged();
            }
        }
        private global::System.DateTime _ProcessedDate;
        partial void OnProcessedDateChanging(global::System.DateTime value);
        partial void OnProcessedDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ICN_NumberSearchModel", Name="vw_NumbersAndOperators")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_NumbersAndOperators : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vw_NumbersAndOperators object.
        /// </summary>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="numberOperatorID">Initial value of the NumberOperatorID property.</param>
        /// <param name="operatorID">Initial value of the OperatorID property.</param>
        /// <param name="numberID">Initial value of the NumberID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static vw_NumbersAndOperators Createvw_NumbersAndOperators(global::System.String number, global::System.Int64 numberOperatorID, global::System.Int32 operatorID, global::System.Int64 numberID, global::System.String name)
        {
            vw_NumbersAndOperators vw_NumbersAndOperators = new vw_NumbersAndOperators();
            vw_NumbersAndOperators.Number = number;
            vw_NumbersAndOperators.NumberOperatorID = numberOperatorID;
            vw_NumbersAndOperators.OperatorID = operatorID;
            vw_NumbersAndOperators.NumberID = numberID;
            vw_NumbersAndOperators.Name = name;
            return vw_NumbersAndOperators;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Number
        {
            get
            {
                return _Number;
            }
            set
            {
                if (_Number != value)
                {
                    OnNumberChanging(value);
                    ReportPropertyChanging("Number");
                    _Number = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Number");
                    OnNumberChanged();
                }
            }
        }
        private global::System.String _Number;
        partial void OnNumberChanging(global::System.String value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 NumberOperatorID
        {
            get
            {
                return _NumberOperatorID;
            }
            set
            {
                if (_NumberOperatorID != value)
                {
                    OnNumberOperatorIDChanging(value);
                    ReportPropertyChanging("NumberOperatorID");
                    _NumberOperatorID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NumberOperatorID");
                    OnNumberOperatorIDChanged();
                }
            }
        }
        private global::System.Int64 _NumberOperatorID;
        partial void OnNumberOperatorIDChanging(global::System.Int64 value);
        partial void OnNumberOperatorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OperatorID
        {
            get
            {
                return _OperatorID;
            }
            set
            {
                if (_OperatorID != value)
                {
                    OnOperatorIDChanging(value);
                    ReportPropertyChanging("OperatorID");
                    _OperatorID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OperatorID");
                    OnOperatorIDChanged();
                }
            }
        }
        private global::System.Int32 _OperatorID;
        partial void OnOperatorIDChanging(global::System.Int32 value);
        partial void OnOperatorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 NumberID
        {
            get
            {
                return _NumberID;
            }
            set
            {
                if (_NumberID != value)
                {
                    OnNumberIDChanging(value);
                    ReportPropertyChanging("NumberID");
                    _NumberID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NumberID");
                    OnNumberIDChanged();
                }
            }
        }
        private global::System.Int64 _NumberID;
        partial void OnNumberIDChanging(global::System.Int64 value);
        partial void OnNumberIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String port_completion_time
        {
            get
            {
                return _port_completion_time;
            }
            set
            {
                Onport_completion_timeChanging(value);
                ReportPropertyChanging("port_completion_time");
                _port_completion_time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("port_completion_time");
                Onport_completion_timeChanged();
            }
        }
        private global::System.String _port_completion_time;
        partial void Onport_completion_timeChanging(global::System.String value);
        partial void Onport_completion_timeChanged();

        #endregion

    
    }

    #endregion

    
}
